package rental_history_rules

//list any import classes here.
import main.facts.Rental;
import main.facts.Customer;
import main.facts.RentalHistory;
import main.facts.SearchHistory;
import main.facts.Vehicle;

import main.dto.SearchDTO;

rule "Update users rental history"
    when
        Rental($customer: customer, $vehicle: vehicle)
    then
    	System.out.println($customer.getRentalHistory());
    	$customer.getRentalHistory().updateRentalHistory($vehicle);
    	System.out.println($customer.getRentalHistory());
        System.out.println("Rental history updated");
end

rule "Update users search history"
    when
    	$customer: Customer()
        $searchParams: SearchDTO(customer.id == $customer.id)
    then
    	
    	System.out.println($customer);
    	System.out.println($searchParams);
    	System.out.println($customer.getSearchHistory());
    	$customer.getSearchHistory().updateSearchHistory($searchParams);
        System.out.println("Search history updated");
end

