//created on: May 16, 2020
package categorisation_tagging_rule

//list any import classes here.
import main.facts.Vehicle;
import main.facts.Tag;

//declare any global variables here


rule "High fuel consumption tag"
    when
        $vehicle: Vehicle(fuelConsumption >= 12)
        $tag: Tag(name=="High fuel consumption")
    then
    	modify($vehicle){ getTags().add($tag)}
end

rule "Medium fuel consumption tag"
    when
        $vehicle: Vehicle(fuelConsumption < 12, fuelConsumption > 9)
        $tag: Tag(name=="Medium fuel consumption")
    then
    	modify($vehicle){ getTags().add($tag)}
end

rule "Low fuel consumption tag"
    when
        $vehicle: Vehicle(fuelConsumption <= 9)
        $tag: Tag(name=="Low fuel consumption")
    then
    	modify($vehicle){ getTags().add($tag)}
end

rule "Sport engine power tag"
    when
        $vehicle: Vehicle(power*1000/weight >= 174) // w/kg
        $tag: Tag(name=="Sport engine power")
    then
    	modify($vehicle){ getTags().add($tag)}
end

rule "High engine power tag"
    when
        $vehicle: Vehicle(power*1000/weight >= 114)
        $tag: Tag(name=="High engine power")
    then
    	modify($vehicle){ getTags().add($tag)}
end

rule "Medium engine power tag"
    when
        $vehicle: Vehicle(power*1000/weight < 114, power*1000/weight > 49)
        $tag: Tag(name=="Medium engine power")
    then
    	modify($vehicle){ getTags().add($tag)}
end

rule "Low engine power tag"
    when
        $vehicle: Vehicle(power*1000/weight < 49)
        $tag: Tag(name=="Low engine power")
    then
    	modify($vehicle){ getTags().add($tag)}
end
