//created on: May 17, 2020
package recommendation_rules

//list any import classes here.
import main.facts.Customer;
import main.facts.PreferencesRecommendations;
import main.facts.Category;
import main.facts.Tag;
import main.facts.Brand;
import main.facts.Fuel;
import main.facts.Transmission;
import main.facts.CustomerPreferences;
import main.facts.Vehicle;
import main.facts.Recommendations;

//declare any global variables here

rule "Category preference rule"
agenda-group "preferences"
no-loop true
lock-on-active true
    when
        Customer($preferences: preferences, $recommendations: recommendations)
        CustomerPreferences($preferedCategories: categoryList) from $preferences
        
        $vehicle: Vehicle($categories: categories)
        
        Number($preferencesHit : intValue) from accumulate(
                    $c: Category($id: id) from $categories
					and
					Category($c.name == name) from $preferedCategories
                    ,
                    sum($id)
                )
    then
    	modify ($recommendations) {addPreferencesHits($vehicle, $preferencesHit)}

end

rule "Mileage limit preference rule"
agenda-group "preferences"
no-loop true
lock-on-active true
    when
        Customer($preferences: preferences, $recommendations: recommendations)
        CustomerPreferences($preferedMileageLimit: mileageLimit) from $preferences
        $vehicle: Vehicle()

        Vehicle(mileageLimit == -1, $preferedMileageLimit == -1 ) from $vehicle
        or
        Vehicle(mileageLimit != -1, $preferedMileageLimit != -1, mileageLimit >= $preferedMileageLimit) from $vehicle
    then
    	modify ($recommendations) {addPreferencesHits($vehicle, 1)}
end


rule "Tag preference rule"
agenda-group "preferences"
no-loop
lock-on-active true
    when
        Customer($preferences: preferences, $recommendations: recommendations)
        CustomerPreferences($preferedTags: tagList) from $preferences

        $vehicle: Vehicle($tags: tags)

        Number($preferencesHit : intValue) from accumulate(
                    $c: Tag($id: id) from $tags
					and
					Tag($c.name == name) from $preferedTags
                    ,
                    sum($id)
                )
    then
    	modify ($recommendations) {addPreferencesHits($vehicle, $preferencesHit)}
end

rule "Brand preference rule"
agenda-group "preferences"
no-loop
lock-on-active true
    when
        Customer($preferences: preferences, $recommendations: recommendations)
        CustomerPreferences($preferedBrands: brandList) from $preferences

        $vehicle: Vehicle($brand: brand)
        Brand(name == $brand.name) from $preferedBrands
    then
    	modify ($recommendations) {addPreferencesHits($vehicle, 1)}
end

rule "Fuel preference rule"
agenda-group "preferences"
no-loop
lock-on-active true
    when
        Customer($preferences: preferences, $recommendations: recommendations)
        CustomerPreferences($preferedFuels: fuelList) from $preferences

        $vehicle: Vehicle($fuel: fuel)
        Fuel(name == $fuel.name) from $preferedFuels
    then
    	modify ($recommendations) {addPreferencesHits($vehicle, 1)}
end


rule "Transmission preference rule"
agenda-group "preferences"
no-loop
lock-on-active true
    when
        Customer($preferences: preferences, $recommendations: recommendations)
        CustomerPreferences($preferedTransmissions: transmissionList) from $preferences

        $vehicle: Vehicle($transmission: transmission)
        Transmission(name == $transmission.name) from $preferedTransmissions
    then
    	modify ($recommendations) {addPreferencesHits($vehicle, 1)}
end

rule "Seats number preference rule"
agenda-group "preferences"
no-loop
lock-on-active true
    when
        Customer($preferences: preferences, $recommendations: recommendations)
        CustomerPreferences($preferedSeatsNo: seatsNo) from $preferences

        $vehicle: Vehicle($preferedSeatsNo == seatsNo)
    then
    	modify ($recommendations) {addPreferencesHits($vehicle, 1)}
end

rule "Door number preference rule"
agenda-group "preferences"
no-loop
lock-on-active true
    when
        Customer($preferences: preferences, $recommendations: recommendations)
        CustomerPreferences($preferedDoorNo: doorNo) from $preferences

        $vehicle: Vehicle($preferedDoorNo == doorNo)
    then
    	modify ($recommendations) {addPreferencesHits($vehicle, 1)}
end

rule "Fuel consumption preference rule"
agenda-group "preferences"
no-loop
lock-on-active true
    when
        Customer($preferences: preferences, $recommendations: recommendations)
        CustomerPreferences($preferedFuelConsumption: fuelConsumption) from $preferences

        $vehicle: Vehicle($preferedFuelConsumption >= fuelConsumption)
    then
    	modify ($recommendations) {addPreferencesHits($vehicle, 1)}
end
